# Site settings
title: Daniel Wenzel
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://daniel-wenzel.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Daniel Wenzel
user_description: I am a graduate student in Information Systems Management from Berlin. I am interested in data analysis, cloud computing, AI and business intelligence. I am also vice president of the student entrepreneurship club <a href="http://start-berlin.com">START Berlin</a>.
user_title: I analyze data.
email: daniel@wenzel.space
# twitter_username: lorem_ipsum
github_username:  daniel-wenzel
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
